local overlay = require("ai-review.overlay")

describe("ai-review.overlay.decorate", function()
  it("marks a draft with DiagnosticWarn + draft tag", function()
    local hl, tag = overlay.decorate({ status = "draft", kind = "suggestion" })
    assert.are.equal("DiagnosticWarn", hl)
    assert.are.equal(" draft", tag)
  end)
  it("marks a verified suggestion with DiagnosticOk + check", function()
    local hl, tag = overlay.decorate({ status = "verified", kind = "suggestion" })
    assert.are.equal("DiagnosticOk", hl)
    assert.are.equal(" ✓", tag)
  end)
  it("marks a plain comment with Comment + no tag", function()
    local hl, tag = overlay.decorate({ status = "verified", kind = "comment" })
    assert.are.equal("Comment", hl)
    assert.are.equal("", tag)
  end)
end)
